# Generated by Django 3.1.7 on 2021-03-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic_analyze', '0003_auto_20210314_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='joined_at',
        ),
    ]
