# Generated by Django 3.1.7 on 2021-03-14 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosmetic_analyze', '0005_profile_joined_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='nickname',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='Profile_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
